### ISSUE TITLE
Failed to connect to petermeissner.de port 8880: Connection refused

### ISSUE THREAD

**Issue by saschagobel** [petermeissner/wikipediatrend#35]
Hi Peter,

awesome package, I'm glad that wikipediatrend is back. I tried it a few weeks ago and it worked great, except for some weird encoding issues. I wanted to replicate this and post an issue but now I receive the following error message:

```r 
trend_data <- 
  wp_trend(
    page = c("Der_Spiegel", "Die_Zeit"), 
    lang = c("de", "en"), 
    from = "2007-01-01",
    to   = Sys.Date()
  )
```

>Error in curl::curl_fetch_memory(url, handle = handle) : 
  Failed to connect to petermeissner.de port 8880: Connection refused

I'll get back to the encoding issue once this is solved. Thx!

**Comment by petermeissner** [comment]
Hmm, that's weird looks like the server is down.

Sascha Göbel <notifications@github.com> schrieb am Mi., 17. Apr. 2019,
11:06:

**Comment by jhofman** [comment]
Seeing this as well. Any chance the server will be back up any time soon?

**Comment by petermeissner** [comment]
Should be resolved. Server is back up (was not started after reboot, I guess).

**Comment by jhofman** [comment]
Thanks for the reply on this. I'm still seeing a refused connection, both in R and directly:

    > trend_data <-
    wp_trend(
      page = c("Iraq"),
      lang = "en",
      from = "2007-01-01",
      to   = Sys.Date()
    )
    Error in curl::curl_fetch_memory(url, handle = handle) : 
    Failed to connect to petermeissner.de port 8880: Connection refused

    $ curl http://petermeissner.de:8880/article/exact/en/Iraq
    curl: (7) Failed to connect to petermeissner.de port 8880: Connection refused

**Comment by petermeissner** [comment]
Thanks. Confirmed. 

Something is off ... should work for now. 

I keep this open for further reporting and as a reminder for further investigation.

**Comment by jhofman** [comment]
Great, working now. Thanks!

**Comment by jhofman** [comment]
@petermeissner: Looks like the server is down again.

I have some students depending on it for a final project, so anything you could do to get it back up and running would be greatly appreciated.

Thanks in advance!

**Comment by petermeissner** [comment]
Should be up and running again. Sorry, it's a very side project only - limited by time and money but especially time - but I am working on a better way to ensure the service is actually running.

**Comment by jhofman** [comment]
No worries, appreciate the support (especially on the weekend)!

I'm seeing the server now, but getting an empty reply. Any idea what might be going on?

    $ curl http://petermeissner.de:8880/article/exact/en/Iraq
    curl: (52) Empty reply from server

Thanks again.

**Comment by petermeissner** [comment]
- Confirmed 
- Should be fixed now (again)

... we are getting there, one step more robust at a time.

**Comment by jhofman** [comment]
Fantastic. Thanks so much!
